openapi: 3.0.0
info:
  title: To-Do Application API
  version: 1.0.0
paths:
  /todos:
    get:
      summary: List all to-dos
      responses:
        '200':
          description: A list of to-dos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'

    post:
      summary: Create a new to-do
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoInput'
      responses:
        '201':
          description: Created

  /todos/{todoId}:
    get:
      summary: Get a to-do by ID
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A single to-do
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'

    put:
      summary: Update a to-do by ID
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '200':
          description: Updated

    delete:
      summary: Delete a to-do by ID
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Deleted

components:
  schemas:
    ToDo:
      type: object
      required:
        - id
        - description
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        completed:
          type: boolean
    ToDoInput:
      type: object
      required:
        - description
      properties:
        description:
          type: string
