/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/todos": {
    /** List all to-dos */
    get: {
      responses: {
        /** @description A list of to-dos */
        200: {
          content: {
            "application/json": components["schemas"]["ToDo"][];
          };
        };
      };
    };
    /** Create a new to-do */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ToDoInput"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: never;
        };
      };
    };
  };
  "/todos/{todoId}": {
    /** Get a to-do by ID */
    get: {
      parameters: {
        path: {
          todoId: string;
        };
      };
      responses: {
        /** @description A single to-do */
        200: {
          content: {
            "application/json": components["schemas"]["ToDo"];
          };
        };
      };
    };
    /** Update a to-do by ID */
    put: {
      parameters: {
        path: {
          todoId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ToDo"];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          content: never;
        };
      };
    };
    /** Delete a to-do by ID */
    delete: {
      parameters: {
        path: {
          todoId: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ToDo: {
      /** Format: uuid */
      id: string;
      description: string;
      completed?: boolean;
    };
    ToDoInput: {
      description: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
